parameters:
  - name: relativePathToTerraformFiles
    type: string
  - name: RunValidate
    type: boolean
    default: true

stages:
  - stage: Build
    variables:
      CheckOutPathTerraformFiles: $(Build.SourcesDirectory)/TerraformFiles
      relativePathToTerraformFiles: $(CheckOutPathTerraformFiles)/${{ parameters.relativePathToTerraformFiles }}
    displayName: "Build"
    jobs:
      - job: PublishTerraformArtifact
        container: TerraformContainer
        workspace:
          clean: all
        displayName: "Publish Terraform Artifact"
        steps:
          - checkout: InfrastructurePipelineTemplate
            persistCredentials: true
            path: $(CheckOutPath)

          - checkout: self
            path: $(CheckOutPathTerraformFiles)
              
          - task: PowerShell@2
            name: validate
            condition: ${{ parameters.RunValidate }}
            displayName: "Terraform Validate"
            inputs:
              targetType: filePath
              filePath: "$(Pipeline.Workspace)/$(CheckOutPath)/pwsh/Invoke-TerraformValidate.ps1"
              arguments: >
                -TerraformFilesDirectory "$(relativePathToTerraformFiles)"            
  
          - task: PublishPipelineArtifact@1
            displayName: "Publish Terraform Artifact"
            inputs:
              targetPath: $(relativePathToTerraformFiles)
              artifact: "TerraformArtifact"
              publishLocation: "pipeline"