parameters:
  - name: environment
    type: string
    default: 'dev'
  - name: Condition
    type: string
    default: 'succeeded()'
  - name: dependsOn
    type: object
    default: { }
  - name: tfStateBlobName
    type: string
  - name: tfStateResourceGroupName
    type: string
  - name: tfStateStorageAccountName
    type: string
  - name: tfStateContainerName
    type: string
  - name: jobsVariableMappings
    type: object
  - name: terraformVariableMappings
    type: object

stages:
  - stage: Deploy_${{ parameters.environment }}
    displayName: "Deploy ${{ parameters.environment }}"
    condition: ${{ parameters.condition }}
    dependsOn:
      - ${{ each dependsOnThis in parameters.dependsOn }}:
          - ${{ dependsOnThis }}
    jobs:
      - template: template.yml@GatedInfrastructureDeploy
        parameters:
          AzDOEnvironmentName: ${{ parameters.environment }}
          TFStateResourceGroupName: ${{ parameters.tfStateResourceGroup }}
          TFStateStorageAccountName: ${{ parameters.tfStateStorageAccountName }}
          TFStateContainerName: ${{ parameters.tfStateContainerName }}
          TFStateBlobName: ${{ parameters.tfStateBlobName }}
          TerraformWorkspace: ${{ parameters.environment }}
          TerraformArtifactConfigRelativePath: "/"
          TerraformArtifact: "TerraformArtifact" # Hardcoded until it doesn't need to be
          TerraformContainer: TerraformContainer
          JobsVariableMappings: ${{ parameters.jobsVariableMappings }}
          TerraformVariableMappings: ${{ parameters.jobsVariableMappings }}