parameters:
  - name: PipelineVariableMappings
    type: object
    default: {}
  - name: relativePathToTerraformFiles
    type: string
  # relativePathToTerraformFiles will be used in two places
  # - Build, where the files are checkout to a specified folder due to double checkout in the Build stage (target repo for terraform files, this repo for pwsh)
  # - Checks, where the files are checkout to default folder due to single checkout and not needing to checkout other repos
  - name: tfStateResourceGroupName
    type: string
  - name: tfStateStorageAccountName
    type: string
  - name: tfStateContainerName
    type: string
  - name: tfStateBlobName
    type: string
  - name: jobsVariableMappings
    type: object
    default: {}
  - name: terraformVariableMappings
    type: object
    default: {}

resources:
  repositories:
    - repository: UKHOTemplates
      type: github
      endpoint: sentonnes
      name: sentonnes/devops-pipelinetemplates
      ref: refs/heads/main
    - repository: GatedInfrastructureDeploy
      type: github
      endpoint: sentonnes
      name: sentonnes/devops-gated-infrastructure-deploy
      ref: refs/heads/main
  containers:
    - container: TerraformContainer
      image: ukhydrographicoffice/terraform-powershell:latest

variables:
  - name: BuildCounter
    value: $[counter(format('{0:yyyyMMdd}', pipeline.startTime), 1)]
  - name: TemplateRepoCheckOutPathSegment
    value: devops-infrastructure-pipeline-template
  - ${{ each PipelineVariableMapping in parameters.PipelineVariableMappings }}:
    - name: ${{ PipelineVariableMapping.Key }}
      value: ${{ PipelineVariableMapping.Value }}

stages:
  - template: build-stage.yml
    parameters:
      relativePathToTerraformFiles: ${{ parameters.relativePathToTerraformFiles }}

  - template: checks-stage.yml
    parameters:
      relativePathToTerraformFiles: ${{ parameters.relativePathToTerraformFiles }}

  - template: deploy-stage.yml
    parameters:
      environment: dev
      dependsOn:
        - "Build"
      tfStateBlobName: ${{ parameters.tfStateBlobName }}
      tfStateResourceGroupName: ${{ parameters.tfStateResourceGroupName }}
      tfStateStorageAccountName: ${{ parameters.tfStateStorageAccountName }}
      tfStateContainerName: ${{ parameters.tfStateContainerName }}
      jobsVariableMappings: ${{ parameters.jobsVariableMappings }}
      terraformVariableMappings: ${{ parameters.terraformVariableMappings }}

  - template: deploy-stage.yml
    parameters:
      environment: qa
      dependsOn:
        - "Checks"
        - "Deploy_dev"
      condition: succeeded('Checks', 'Deploy_dev')
      tfStateBlobName: ${{ parameters.tfStateBlobName }}
      tfStateResourceGroupName: ${{ parameters.tfStateResourceGroupName }}
      tfStateStorageAccountName: ${{ parameters.tfStateStorageAccountName }}
      tfStateContainerName: ${{ parameters.tfStateContainerName }}
      jobsVariableMappings: ${{ parameters.jobsVariableMappings }}
      terraformVariableMappings: ${{ parameters.terraformVariableMappings }}

  - template: deploy-stage.yml
    parameters:
      environment: live
      dependsOn:
        - "Deploy_qa"
      tfStateBlobName: ${{ parameters.tfStateBlobName }}
      tfStateResourceGroupName: ${{ parameters.tfStateResourceGroupName }}
      tfStateStorageAccountName: ${{ parameters.tfStateStorageAccountName }}
      tfStateContainerName: ${{ parameters.tfStateContainerName }}
      jobsVariableMappings: ${{ parameters.jobsVariableMappings }}
      terraformVariableMappings: ${{ parameters.terraformVariableMappings }}
