parameters:
  - name: relativePathToTerraformFiles
    type: string
  - name: tfStateResourceGroupName
    type: string
  - name: tfStateStorageAccountName
    type: string
  - name: tfStateContainerName
    type: string
  - name: tfStateBlobName
    type: string
  - name: jobsVariableMappings
    type: object
  - name: terraformVariableMappings
    type: object

resources:
  repositories:
    - repository: UKHOTemplates
      type: github
      endpoint: sentonnes
      name: sentonnes/devops-pipelinetemplates
      ref: refs/heads/main
    - repository: GatedInfrastructureDeploy
      type: github
      endpoint: sentonnes
      name: sentonnes/devops-gated-infrastructure-deploy
      ref: refs/heads/feature/replace-variablesTemplateRelativePath
  containers:
    - container: TerraformContainer
      image: ukhydrographicoffice/terraform-powershell:1.8.5

stages:
  - template: build-stage.yml
    parameters:
      relativePathToTerraformFiles: ${{ parameters.relativePathToTerraformFiles }}

  - template: checks-stage.yml
    parameters:
      relativePathToTerraformFiles: ${{ parameters.relativePathToTerraformFiles }}

  - template: deploy-stage.yml
    parameters:
      environment: dev
      dependsOn:
        - "Build"
      tfStateBlobName: ${{ parameters.tfStateBlobName }}
      tfStateResourceGroupName: ${{ parameters.tfStateResourceGroupName }}
      tfStateStorageAccountName: ${{ parameters.tfStateStorageAccountName }}
      tfStateContainerName: ${{ parameters.tfStateContainerName }}
      jobsVariableMappings: ${{ parameters.jobsVariableMappings }}
      terraformVariableMappings: ${{ parameters.terraformVariableMappings }}

  - template: deploy-stage.yml
    parameters:
      environment: qa
      dependsOn:
        - "Checks"
        - "Deploy_dev"
      condition: succeeded('Checks', 'Deploy_dev')
      tfStateBlobName: ${{ parameters.tfStateBlobName }}
      tfStateResourceGroupName: ${{ parameters.tfStateResourceGroupName }}
      tfStateStorageAccountName: ${{ parameters.tfStateStorageAccountName }}
      tfStateContainerName: ${{ parameters.tfStateContainerName }}
      jobsVariableMappings: ${{ parameters.jobsVariableMappings }}
      terraformVariableMappings: ${{ parameters.terraformVariableMappings }}

  - template: deploy-stage.yml
    parameters:
      environment: live
      dependsOn:
        - "Deploy_qa"
      tfStateBlobName: ${{ parameters.tfStateBlobName }}
      tfStateResourceGroupName: ${{ parameters.tfStateResourceGroupName }}
      tfStateStorageAccountName: ${{ parameters.tfStateStorageAccountName }}
      tfStateContainerName: ${{ parameters.tfStateContainerName }}
      jobsVariableMappings: ${{ parameters.jobsVariableMappings }}
      terraformVariableMappings: ${{ parameters.terraformVariableMappings }}