name: $(BuildDefinitionName)_$(SourceBranchName)_$(Date:yy)$(DayOfYear).$(BuildCounter)

pr:
  autoCancel: true # indicates whether additional pushes to a PR should cancel in-progress runs for the same PR. Defaults to true
  branches:
    include:
      - '*'
  paths:
    include:
      - ../folder/files/*

trigger:
  branches:
    include:
      - main
      - 'feat*/*/main' # allow feature main branches
      - 'Feat*/*/main'
      - 'bug*/*/main' # allow bugfix main branches
      - 'Bug*/*/main'
      - 'fix*/*/main' # allow hotfix main branches
      - 'Fix*/*/main'

variables:
  - name: BuildCounter
    value: $[counter(format('{0:yyyyMMdd}', pipeline.startTime), 1)]
  - name: UbuntuPool
    value: "Mare Nectaris"
  - template: infrastructure-mappings.yml

pool: $(UbuntuPool)

resources:
  repositories:
    - repository: InfrastructurePipelineTemplate
      type: github
      endpoint: sentonnes
      name: sentonnes/devops-infrastructure-pipeline-template
      
# pipeline config above can not be set in the template

extends:
  template: pipeline.yml@InfrastructurePipeline 
  parameters:
    relativePathToTerraformFiles: ../folder/files 
    tfStateResourceGroupName: rg
    tfStateStorageAccountName: strgacc
    tfStateContainerName: container
    tfStateBlobName: tfstate
    jobsVariableMappings: ${{ variables.JobsVariableMappings }}
    terraformVariableMappings: ${{ variables.TerraformVariableMappings }}

      
